#! /usr/bin/env python3
"""
# archiveGMData is part of EQdyna. 
# It moves gm related raw data to folder gmData.
"""

import sys, os
from gmFuncLib import * 

def archiveGMData():
    
    def Error_Message():
        print( " ")
        print( "Usage: landmask region_cut[0/10600/0/27648]")  
        
    print('ArchiveGMData - START ... ...')
    n = len(sys.argv)
    #if n!=2:
    #    print('FILTER: Wrong # of input arguments; # should be 1 ... ...')
    #    Error_Message()
    os.system('mkdir gmData')
    for i in range(10000):
        if os.path.isfile('gm'+str(i))==True:
            os.system('mv gm'+str(i)+' gmData')
        if os.path.isfile('surface_coor.txt'+str(i))==True:
            os.system('mv surface_coor.txt'+str(i)+' gmData')
    
    os.system('cp -r user_defined_params.py defaultParameters.py lib.py gmData')
    print("ArchiveGMData - END ... ...")

def _main_func(description):
    archiveGMData()

if __name__ == "__main__":
    _main_func(__doc__)

